version: 1.0.{build}

clone_depth: 10

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  matrix:
    - ruby_folder_version: "22"
      platform: "x86"

init:
- ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
- ps: (New-Object Net.WebClient).DownloadFile('http://curl.haxx.se/ca/cacert.pem', "$env:temp\cacert.pem")
- ps: $env:SSL_CERT_FILE = "$env:temp\cacert.pem"

install:
  - SET "PATH=C:\Ruby%ruby_folder_version%\bin;%PATH%"
  - bundle install --retry 3 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle
  #- ps: Install-Product node "8" $env:platform
  #- npm install

build: off

test_script:
  - ruby -v
  - gem -v
  - bundle -v
  - node -v
  - npm -v
  - java -version
  - npm test

matrix:
  fast_finish: true
